### ISSUE TITLE
How add a plugin?

### ISSUE THREAD

**Issue by jdnichollsc** [miamarti/ng.ckeditor#10]
Hi man

I need to add a plugin, is possible? Any example? =)

Thanks in advance, Nicholls

**Comment by miamarti** [comment]
By the time I had no opportunity to implement the accretion of plugins.

**Comment by miamarti** [comment]
Hi,
In version 2.0.0 you can use the "ng-config"' option to enter a configuration object to your liking.
I hope it helped you. Any problem I am available.

**Comment by jdnichollsc** [comment]
Thanks! :+1:
