### ISSUE TITLE
Is something broken in v2?

### ISSUE THREAD

**Issue by steveharan** [miamarti/ng.ckeditor#11]
We are now getting this:

http://puu.sh/q8iJS/0536b781ff.png

**Comment by steveharan** [comment]
Changed bind to ng-model as per doc, now getting this:

http://puu.sh/q8j6J/ef842f28db.png

Can we go back to v1?

**Comment by miamarti** [comment]
The ng-bind attribute was replaced by ng-model

**Comment by miamarti** [comment]
http://jsfiddle.net/miamarti/q4ma86c1/156/?utm_source=website&utm_medium=embed&utm_campaign=q4ma86c1
