### ISSUE TITLE
Bug with msn-count

### ISSUE THREAD

**Issue by jmtt89** [miamarti/ng.ckeditor#12]
very ugly bug when remove msn-count="Number of typed characters:" from the tag

can try in your own jsfindle  http://jsfiddle.net/z5m9pL0d/

**Comment by miamarti** [comment]
Hello,
Thanks for the support.
Please see if the bug persists in v2.0.1 version

**Comment by jmtt89** [comment]
Hi @miamarti all works fine now thanks :)

**Comment by miamarti** [comment]
I who thank @jmtt89

Need help just call.
I get online by [chat](https://gitter.im/miamarti/ng.ckeditor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) as well.
