### ISSUE TITLE
Scayt?

### ISSUE THREAD

**Issue by steveharan** [miamarti/ng.ckeditor#13]
I have this in for my options:

        $scope.editorOptions = [
            { name: 'document', items: ['NewPage', 'Preview'] },
            { name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'] },
            { name: 'editing', items: ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt'] },
etc

The editor looks like this:

https://puu.sh/r8wQJ/ee7c3e0049.png

So it seems to be identifying the spelling mistakes, but the right click only has 'cut and paste' and there is no 'abc' menu option with the Scayt submenu.

Hope you can help!  Thanks

Steve

**Comment by steveharan** [comment]
In fact changing the options to:

        $scope.editorOptions = [
        {
            name: 'editing', items: ['Scayt']
        }
        ];

Has 0 effect - I still have the full list above!  How can I control which options I have in the editor please?

**Comment by steveharan** [comment]
Done it!

**Comment by miamarti** [comment]
Hi @steveharan,

You can use the tags below to remove buttons and desattivar plugins:
` remove-buttons="Image" remove-plugins="iframe,flash,smiley"`

I hope it helps.

**Comment by steveharan** [comment]
Scayt:

http://ckeditor.com/addon/scayt <http://ckeditor.com/addon/scayt>

Thanks, sorted now.
