### ISSUE TITLE
simpleEditor attribute not working

### ISSUE THREAD

**Issue by karen-hikesupport** [miamarti/ng.ckeditor#14]
Hi ,

can u give me answer about simpleEditor not working

**Comment by miamarti** [comment]
Hello @karen-hikesupport,

Take a look at the example below, believe that help:
http://jsfiddle.net/miamarti/kku51f2c/

Here are some steps that can help:

1. Navigate to the root folder of the Front End project;
2. Open a terminal and type the following command: `bower install ng.ckeditor --save`;
3. Go to your AngularJS project and its main module, inject ng.ckeditor (sample: `angular.module('example', ["ng.ckeditor"]);`);
4. In its view, enter the publisher tag, informing the ng-model and the plugins or buttons you want to remove. If you do not want to remove anything, these tags are optional. See the example below:

```
      <ng-ckeditor 
              ng-model="htmlEditor" 
              remove-buttons="Image" 
              remove-plugins="iframe,flash,smiley">
      </ng-ckeditor>
```

Or

```
      <ng-ckeditor ng-model="htmlEditor"></ng-ckeditor>
```

I think this will be enough for your project work.

I have helped =)

**Comment by vhanla** [comment]
With HTML5 URL mode enabled it tries to load config.js, lang, etc. from relative path which of course doesn't exist. BTW it is showing Error code: editor-incorrect-destroy.

**Comment by miamarti** [comment]
Thanks for the report @vhanla;
I'll check as soon as possible.
Greetings :+1:
