### ISSUE TITLE
Possible problem with gulp on production code

### ISSUE THREAD

**Issue by caian-gums** [miamarti/ng.ckeditor#17]
Hey, I'm trying to use this plugin on my code and all goes ok.

The problem is when I try to generate the production code with gulp and generates an Warning and doesn't load the editor itself. The error is `editor-incorrect-destroy` and I saw some users that use Rails and could solve this.

Any help?

**Comment by miamarti** [comment]
Hi,
I use Grunt to generate as builds.
I'm going to investigate here, too. If I know anything I'll get in touch.

Thank you

**Comment by caian-gums** [comment]
![image](https://cloud.githubusercontent.com/assets/7551787/24311865/ca2466f2-10b4-11e7-9704-ac7e4a761c5b.png)

Forgot to post the image of error

**Comment by miamarti** [comment]
Disable uglify and try again

**Comment by caian-gums** [comment]
The error still the same. The problem is just when I use gulp and generate production code. When I use on my dev code locally, it works.

Thanks for your help but I think I'll try another text editor. The problem seems to be with CKEditor as I searched...

**Comment by miamarti** [comment]
I had this problem once with him. It was the minification that needed to be disabled only for the publisher.

**Comment by dschuermans** [comment]
I've had and have the exact same issue.

if @caian-gums is bundling his files, ckeditor tries to load config.js and contents.css from the current url.
In my case, it had to load files from https://domain.com/lib/ckeditor/... but was trying to load from https://domain.com/current/url/at/which/we/are/viewing/config.js

Adding CKEDITOR_BASEPATH in my index.html **before ckeditor files are loaded** solved this issue, see http://docs.ckeditor.com/#!/guide/dev_basepath for more information.
In my case, I set it to /lib/ckeditor

I'm still curious about the editor-incorrect-destroy warnings/errors though...
Any idea @miamarti?
