### ISSUE TITLE
Source View Data is Stale

### ISSUE THREAD

**Issue by xamino** [miamarti/ng.ckeditor#21]
When modifying via the source view we seem to be working on a stale version of the data, meaning the model isn't updated accordingly. To actually get it to apply we have to switch out of the source mode to trigger a refresh. (For us this manifests such that when the user is done editing the source and hits  save, the content we get out of the model does not reflect those changes.)

These changes remove the need for that by also updating the model on key events. Note that we need the $timeout to get the data only after the key-up event (otherwise the update will be missing the last key press entry).

**Comment by xamino** [comment]
Thanks for the fast response! Could you please also publish the new release to npm, then I can remove the dependency on my own repo... :grin:

**Comment by miamarti** [comment]
@xamino npm Done :+1:
