### ISSUE TITLE
Timeout on ngModel change has side-effect

### ISSUE THREAD

**Issue by xamino** [miamarti/ng.ckeditor#22]
This originates from [this](https://github.com/miamarti/ng.ckeditor/blob/master/dist/ng-ckeditor.js#L114) line.

# The Problem

We have a dictionary bound to the model in our case where the key is the current language:
```html
<ng-ckeditor ng-model="translations[language]"></ng-ckeditor>
```
This works perfectly fine until you start switching the language, potentially rapidly. If you switch from one to the other and then back in under a second, the CKeditor is set to the wrong data (the text from the "other" translation).

# The Exact Issue

What happens exactly in this case is, to the best of our ability to test this, as follows:
* ngModel is changed
* $watch on ngModel fires
* value is different than current content, so setValue is called
* setValue clears previous timeouts and then creates one for setting this new data

Now we break it:
* before the current timeout is finished, we update ngModel again (so any further change < 1 sec)
* $watch on ngModel fires
* value is now the same (!) as the contents of CKeditor because data hasn't been set yet (timeout hasn't fired yet)
* setValue is thus *not* called (which would invalidate the previous pending timeout)

And now the first timeout actually fires, setting the data for the original model state to the unwanted state of the interim value.

# Proposed Fixes

I have two proposed fixes, depending on the logic behind the existing code:

1. call clearInterval() as part of the $watch handling:

```js
scope.$watch('ngModel', function(value) {
    clearInterval(interval);
    if (value !== editor.getData()) {
        setValue(value, editor);
    }
});
```

2. Remove the setValue function entirely and just directly set the value:

```js
scope.$watch('ngModel', function(value) {
    if (value !== editor.getData()) {
        editor.setData(value || '');
    }
});
```
I think I'd prefer 2 because I don't know what the purpose of the one second interval is (it's also a bit long for my taste). Is it an implementation of a manual debounce (which ng-model [is capable of](https://code.angularjs.org/1.3.20/docs/api/ng/directive/ngModelOptions) by itself for Angular >1.3) or does it have some other purpose?

I can do another PR for either or, depending on which version would be the better one. :grin:

**Comment by miamarti** [comment]
Hi @xamino 
Let's go in the line of the first proposal, with the 'clearInterval'.
I even got clearInterval, but this caused me problems, I just do not remember what the problem was.

I'm pretty busy here this semester.
I ended up not being able to focus too much on the tests.
I'm going to work on a general overhaul of the policy, and I already remove the $interval

**Comment by xamino** [comment]
PR with the fix (for now) now there. Thanks for quick feedback!

Looking forward to the general overhaul, once you have time. :+1:

**Comment by xamino** [comment]
Thanks a ton for the fast release! NPM hasn't updated yet, does that just take a while for the update to show?

**Comment by stephanbarrett** [comment]
Looking for the latest version on NPM as well. https://www.npmjs.com/package/ng-ckeditor shows 2.03 instead of 2.04.
