### ISSUE TITLE
Support for inline editing (contenteditable)?

### ISSUE THREAD

**Issue by filipesilva** [miamarti/ng.ckeditor#3]
Can this directive be used in elements that have `contenteditable="true"` for inline editing? I checked the source and it seems to not be usable as attribute.

**Comment by jdnichollsc** [comment]
+1

**Comment by miamarti** [comment]
I'm sorry, I'm alone with the commits, to end up getting overwhelmed.
It really was not implemented, I will include as quickly as possible.
Thanks for the collaboration.

**Comment by miamarti** [comment]
Hi,
In version 2.0.0 you can use the "ng-config"' option to enter a configuration object to your liking.
I hope it helped you. Any problem I am available.

**Comment by filipesilva** [comment]
Thank you so much for adding that option, cheers!

**Comment by jdnichollsc** [comment]
Cool!

**Comment by FradaL** [comment]
Excuse me, do you have any examples of how the object should pass in the ng-config to use the inline ckeditor?
