### ISSUE TITLE
Dependency link of cdn in readme gives 404 not found

### ISSUE THREAD

**Issue by tasawar-hussain** [miamarti/ng.ckeditor#30]
[https://cdnjs.cloudflare.com/ajax/libs/miamarti-ng-ckeditor/2.0.2/ng-ckeditor.min.js]() it does not work anymore
instead use 
for minified 
[https://cdnjs.cloudflare.com/ajax/libs/ng.ckeditor/2.0.4/ng-ckeditor.min.js]()
for complete
https://cdnjs.cloudflare.com/ajax/libs/ng.ckeditor/2.0.4/ng-ckeditor.js

**Comment by miamarti** [comment]
Thanks for reporting =)
