### ISSUE TITLE
msnCount bug

### ISSUE THREAD

**Issue by micheleissa** [miamarti/ng.ckeditor#32]
Hello,
nice directive!
There is a bug in line 72 and line 87 element[0] should be elem[0] because elem is the argument name and element is undefined.
![image](https://user-images.githubusercontent.com/16201881/31566193-20fb4d00-b02f-11e7-81ab-315eddd2a14a.png)

**Comment by miamarti** [comment]
Thanks for reporting =)
Bug solved
