### ISSUE TITLE
How to change location in angular-material

### ISSUE THREAD

**Issue by caok2709** [miamarti/ng.ckeditor#4]
<img width="2326" alt="screen shot 2015-08-04 at 5 25 40 pm" src="https://cloud.githubusercontent.com/assets/7703592/9073232/f19b12a8-3acd-11e5-8b1f-5ad97dc52f64.png">

Hi guys... I have two ckeditor in my HTML:
                        
                       <div>
                            <label class="md-title lsForm-label">{{field.label}}</label>
                            <ng-ckeditor
                                         bind="target[field.modelName[0]]"
                                         skin="moono"
                                         remove-buttons="Image"
                                         remove-plugins="iframe,flash,smiley"
                                         msn-count=" Number of typed characters:">
                            </ng-ckeditor>
                        </div>

first of all:   ng-ckeditor bind attribute  can it bind after the page load?  Because I am loading sth to show on the page.  $scope.target is load after page, then I see errors:
1 Uncaught ReferenceError: scope is not defined
If I try to click on source button, the error will +1

Second:    anyone know how to move the location of the ng-ckeditor. ....I tried many ways it seems like it's hard maintain it's location..
I wanna see two ng-ckeditor in the same row.. with some space between them... how to do that..

**Comment by miamarti** [comment]
Hi,

Excellent observation.
This bug has been fixed in version 2.0.0
Please check if this persists.

Thanks for the great help
