### ISSUE TITLE
.min.js  Filfe comepile Error

### ISSUE THREAD

**Issue by caok2709** [miamarti/ng.ckeditor#6]
1. We shouldn't not Shrink variables when creating the .min file.
Because: we use this line
eval('(function(){ scope.' + attrs.bind + ' = evt.editor.getData(); })()');
                             ^
It will say scope is undefined....of course it's undefined  because  shrink tool won't make 'scope' become the shrink variable anyway, it will keep it as  scope.... so... you know....  scope won't be find.

Everything eles seems fine, just don't use shrink will solve the problem. (or you have to assign scope to sth given before)

**Comment by miamarti** [comment]
Hi,
The reflections were removed and replaced by apply, so the minification bug was resolved.
Thank you for your help.
