### ISSUE TITLE
bower error in Visual Studio "no tag found that was able to satisfy ~1.0.1"

### ISSUE THREAD

**Issue by kevinneufeld** [miamarti/ng.ckeditor#8]
FYI unable to select the specific version, in bower I have set to `"ng.ckeditor":"*"` in order to work, would prefer `"ng.ckeditor":"1.0.1"`.

**Comment by miamarti** [comment]
Thanks for the collaboration.
I'm sorry for the delay, I am alone with the commits.
Problem solved.
